<?php
    $lang['number']   = 'Référence';
    $lang['date']     = 'Date';
    $lang['time']     = 'Heure';
    $lang['due']      = 'Date d\'échéance';
    $lang['to']       = 'Facturé à';
    $lang['from']     = 'Facturé par';
    $lang['product']  = 'Produit';
    $lang['qty']      = 'Quantité';
    $lang['price']    = 'Prix';
    $lang['discount'] = 'Promotion';
    $lang['vat']      = 'TVA';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'de';